  # Use root/example as user/password credentials
version: '3.1'

networks:
  app-network:
    driver: brigde

services:


  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  ui:
    build:
      context: ./ui
    restart: always
    ports:
      - 3000:3000

  api:
    build:
      context: ./api
    restart: always
    ports:
      - 8080:8080